### ISSUE TITLE
No CSS styling done for the RSVP page section where the user hasn't logged in.

### ISSUE THREAD

**Issue by nikhilbhardwaj** [nikhilbhardwaj/WeddingWebsite#4]
This text - "You need to be logged in via facebook to RSVP. Click here to log in."
is not styled.

**Comment by deboshrestha** [comment]
But I thought it should be subtle kind of a thing, if you want I will put some.

**Comment by nikhilbhardwaj** [comment]
Yes please, this should also follow the same font and style as any text on the RSVP page would.
Also different pull requests for different issues if possible.

Protip - If you reference the issue in your commit message then merging that in automatically resolves the issue too.
Also you last commit was from an email that it shouldn't have been from. Fix that before you fix anything else.  Please see - https://stackoverflow.com/questions/4220416/can-i-specify-multiple-users-for-myself-in-gitconfig and edit the history if possible too.
